### ISSUE TITLE
JSLint Is Out Of Date

### ISSUE THREAD

**Issue by wyattearp** [mackuba/jslint_on_rails#10]
The JSLint included is from 2010-12-21 and there appear to be numerous fixes from here: https://github.com/douglascrockford/JSLint/commits/master/jslint.js

Sadly, just dropping in a new JSLint file doesn't magically work.

**Comment by mackuba** [comment]
I haven't been updating JSLint for some time, because Crockford did a purge in the options at some point and some of them disappeared, forcing you to do things his way. It seems he later restored some of them, but he also renamed a lot of them or changed their meaning to the opposite (and apparently refactored the code enough to make my runner code stop working).

It looks like it would be a lot of work now to support the new option set, and I'm planning to redesign this anyway when I integrate JSHint too, so I guess there's no point in doing that now only for JSLint if I'll have to change it again later.

**Comment by wyattearp** [comment]
Understood.  Looking forward to when you redesign it.
