### ISSUE TITLE
Local options erroneously apply to other files

### ISSUE THREAD

**Issue by scottj97** [mackuba/jslint_on_rails#7]
I have a few js files with local jslint options set using /*jslint eqeqeq:true */ for example. I expect these options to apply to that one source js file and no others. But it seems that jslint_on_rails applies this option to that file and all subsequent files that it checks. I expected it to reset the options to those specified in the jslint.yml file for each new source file that it checks.

**Comment by scottj97** [comment]
I even tried putting the /*jslint */ options inside a function. According to jslint.com, "the directive respects function scope." Yet it still affected subsequent files.

**Comment by scottj97** [comment]
Ignore previous comment; the "directive respects function scope" behavior was added in jslint edition 2011-03-05; it seems jslint_on_rails is stuck on edition 2010-12-21. Which is a separate issue.

**Comment by mackuba** [comment]
Yeah, I haven't updated it because shortly after the last version Crockford started to make some changes I didn't like, like removing options which I always set etc. I will keep it up to date again once I finish the work on JSHint branch, to make it possible to choose the engine, but I don't know when that will happen. I'll see if I can do any quick fix for now...

**Comment by mackuba** [comment]
This should be fixed in 1.0.7 (I mean the case with per-file options - I don't want to dig into JSLint to fix the per-function options, and I don't want to update JSLint to latest version either).

**Comment by scottj97** [comment]
Excellent. I confirm the fix works for me.
