### ISSUE TITLE
Adding colors

### ISSUE THREAD

**Issue by coffeesam** [mackuba/jslint_on_rails#9]
Hi, 

Is there any chance of adding colors in output?
Red for the Lint warnings. Normal color for the code snippet.
Summary may also be in red if the test fails, green otherwise.

I hope you will consider these recommendations.

Cheers

**Comment by mackuba** [comment]
Sounds like a good idea, I'll think about it :)

**Comment by mackuba** [comment]
Hmm, I've realized I'd have to do that on the Javascript side (in Rhino), because it's Javascript that prints the output. I'll have to leave it until 2.0 then... I'd like to refactor the Javascript running code to make it possible to use multiple JS runners, so I'll be changing a lot of that code anyway.

**Comment by coffeesam** [comment]
Cool =)
